openapi: 3.0.0
info:
    version: 0.0.8
    title: temp
servers:
    - {url: 'https://google.com'}
paths:
    /pets99: {get: {description: 'Does not return all pets from the system that the user has access to', produces: [application/json], responses: {'200': {description: 'A list of pets.'}}}}
